### ISSUE TITLE
Build Tool: Docker

### ISSUE THREAD

**Issue by dinos80152** [liam-lai/ptt-alertor#2]
Deploying Go servers with Docker
https://blog.golang.org/docker

Docker — 从入门到实践
https://yeasy.gitbooks.io/docker_practice/content/

最近Docker淫威太盛，看我怎么扁它！
http://mp.weixin.qq.com/s?__biz=MzA5MjA2MjgyNg==&mid=206354580&idx=1&sn=8faa5ca7f5ddace1234f00516939f66e&scene=1&key=af154fdc40fed0036637bf6fd3481e6b717342819ed3bad879f40aae4bcfe8e297aa83e548e994dbfecb0b5b460be751&ascene=0&uin=MzAyNjUyMTYw&devicetype=iMac+MacBookPro11%2C1+OSX+OSX+10.10.3+build(14D136

**Comment by liam-lai** [comment]
Build Docker
